/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface HostingPaymentV2Interface extends ethers.utils.Interface {
  functions: {
    "Decimal()": FunctionFragment;
    "MaxTotalExpiration()": FunctionFragment;
    "MinExpiration()": FunctionFragment;
    "addCombo((uint256,uint256,uint256,uint256,bytes28,bool))": FunctionFragment;
    "addManager(address)": FunctionFragment;
    "addToken(address)": FunctionFragment;
    "boughtTime(bytes28)": FunctionFragment;
    "buy(bytes28,uint256,uint256,uint256)": FunctionFragment;
    "canBuy(bytes28,uint256)": FunctionFragment;
    "canRenew(bytes28)": FunctionFragment;
    "canUpgrade(bytes28,uint256)": FunctionFragment;
    "channel()": FunctionFragment;
    "comboLength()": FunctionFragment;
    "combos(uint256)": FunctionFragment;
    "cost(bytes28)": FunctionFragment;
    "costToOriginalDecimal(uint256,uint256)": FunctionFragment;
    "decimalMethod()": FunctionFragment;
    "decimals(uint256)": FunctionFragment;
    "expiration(bytes28)": FunctionFragment;
    "expirationAt(bytes28)": FunctionFragment;
    "gId()": FunctionFragment;
    "getComboCost(uint256,uint256)": FunctionFragment;
    "getUpgradeExchange(bytes28,uint256)": FunctionFragment;
    "guid(bytes28)": FunctionFragment;
    "isCustom(uint256)": FunctionFragment;
    "isExpired(bytes28)": FunctionFragment;
    "isManagers(address)": FunctionFragment;
    "level(bytes28)": FunctionFragment;
    "lock()": FunctionFragment;
    "maxTotalRenewExpiration(bytes28)": FunctionFragment;
    "maxTotalUpgradeExpiration(bytes28,uint256)": FunctionFragment;
    "mints()": FunctionFragment;
    "nonces(bytes28)": FunctionFragment;
    "owner()": FunctionFragment;
    "receipts(bytes28)": FunctionFragment;
    "removeManager(address)": FunctionFragment;
    "removeToken(uint256)": FunctionFragment;
    "renew(uint256,bytes28,uint256,uint256)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "serviceId()": FunctionFragment;
    "setMaxTotalExpriation(uint256)": FunctionFragment;
    "setMinExpriation(uint256)": FunctionFragment;
    "to(bytes28)": FunctionFragment;
    "token(bytes28)": FunctionFragment;
    "tokenLength()": FunctionFragment;
    "tokens(uint256)": FunctionFragment;
    "transferChannel(address)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "unlock()": FunctionFragment;
    "updateCombo(uint256,(uint256,uint256,uint256,uint256,bytes28,bool))": FunctionFragment;
    "upgrade(bytes28,uint256,uint256,uint256)": FunctionFragment;
    "validateCombo(uint256)": FunctionFragment;
    "withdraw(address,address,uint256)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "Decimal", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "MaxTotalExpiration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MinExpiration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addCombo",
    values: [
      {
        bandwidth: BigNumberish;
        storageAmount: BigNumberish;
        buildingTime: BigNumberish;
        pricePerMonth: BigNumberish;
        to: BytesLike;
        isValid: boolean;
      }
    ]
  ): string;
  encodeFunctionData(functionFragment: "addManager", values: [string]): string;
  encodeFunctionData(functionFragment: "addToken", values: [string]): string;
  encodeFunctionData(
    functionFragment: "boughtTime",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "buy",
    values: [BytesLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "canBuy",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "canRenew", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "canUpgrade",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "channel", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "comboLength",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "combos",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "cost", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "costToOriginalDecimal",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "decimalMethod",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "decimals",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "expiration",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "expirationAt",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "gId", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getComboCost",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUpgradeExchange",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "guid", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "isCustom",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isExpired",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "isManagers", values: [string]): string;
  encodeFunctionData(functionFragment: "level", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "lock", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "maxTotalRenewExpiration",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "maxTotalUpgradeExpiration",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "mints", values?: undefined): string;
  encodeFunctionData(functionFragment: "nonces", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "receipts", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "removeManager",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "removeToken",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renew",
    values: [BigNumberish, BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "serviceId", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setMaxTotalExpriation",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinExpriation",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "to", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "token", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "tokenLength",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tokens",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferChannel",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "unlock", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateCombo",
    values: [
      BigNumberish,
      {
        bandwidth: BigNumberish;
        storageAmount: BigNumberish;
        buildingTime: BigNumberish;
        pricePerMonth: BigNumberish;
        to: BytesLike;
        isValid: boolean;
      }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "upgrade",
    values: [BytesLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "validateCombo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [string, string, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "Decimal", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "MaxTotalExpiration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MinExpiration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addCombo", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addManager", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "boughtTime", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "buy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "canBuy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "canRenew", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "canUpgrade", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "channel", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "comboLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "combos", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cost", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "costToOriginalDecimal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "decimalMethod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "decimals", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "expiration", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "expirationAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getComboCost",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUpgradeExchange",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "guid", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isCustom", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isExpired", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isManagers", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "level", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lock", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "maxTotalRenewExpiration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxTotalUpgradeExpiration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mints", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nonces", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "receipts", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "renew", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "serviceId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMaxTotalExpriation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMinExpriation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "to", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tokenLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tokens", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferChannel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unlock", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateCombo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "upgrade", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "validateCombo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;

  events: {
    "AddCombo(bytes28,uint256,tuple)": EventFragment;
    "AddManager(address)": EventFragment;
    "AddToken(uint256,address)": EventFragment;
    "Buy(bytes2,bytes2,bytes28,tuple)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "RemoveManager(address)": EventFragment;
    "RemoveToken(uint256,address)": EventFragment;
    "Renew(bytes2,bytes2,bytes28,tuple)": EventFragment;
    "UpdateCombo(bytes28,uint256,tuple)": EventFragment;
    "Upgrade(bytes2,bytes2,bytes28,tuple)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AddCombo"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AddManager"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AddToken"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Buy"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RemoveManager"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RemoveToken"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Renew"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UpdateCombo"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Upgrade"): EventFragment;
}

export type AddComboEvent = TypedEvent<
  [
    string,
    BigNumber,
    [BigNumber, BigNumber, BigNumber, BigNumber, string, boolean] & {
      bandwidth: BigNumber;
      storageAmount: BigNumber;
      buildingTime: BigNumber;
      pricePerMonth: BigNumber;
      to: string;
      isValid: boolean;
    }
  ] & {
    to: string;
    level: BigNumber;
    combo: [BigNumber, BigNumber, BigNumber, BigNumber, string, boolean] & {
      bandwidth: BigNumber;
      storageAmount: BigNumber;
      buildingTime: BigNumber;
      pricePerMonth: BigNumber;
      to: string;
      isValid: boolean;
    };
  }
>;

export type AddManagerEvent = TypedEvent<[string] & { manager: string }>;

export type AddTokenEvent = TypedEvent<
  [BigNumber, string] & { index: BigNumber; token: string }
>;

export type BuyEvent = TypedEvent<
  [
    string,
    string,
    string,
    [string, string, BigNumber, BigNumber, BigNumber, BigNumber] & {
      to: string;
      token: string;
      level: BigNumber;
      boughtTime: BigNumber;
      expiration: BigNumber;
      cost: BigNumber;
    }
  ] & {
    gId_: string;
    serviceId_: string;
    uuid: string;
    receipt: [string, string, BigNumber, BigNumber, BigNumber, BigNumber] & {
      to: string;
      token: string;
      level: BigNumber;
      boughtTime: BigNumber;
      expiration: BigNumber;
      cost: BigNumber;
    };
  }
>;

export type OwnershipTransferredEvent = TypedEvent<
  [string, string] & { previousOwner: string; newOwner: string }
>;

export type RemoveManagerEvent = TypedEvent<[string] & { manager: string }>;

export type RemoveTokenEvent = TypedEvent<
  [BigNumber, string] & { index: BigNumber; token: string }
>;

export type RenewEvent = TypedEvent<
  [
    string,
    string,
    string,
    [string, string, BigNumber, BigNumber, BigNumber, BigNumber] & {
      to: string;
      token: string;
      level: BigNumber;
      boughtTime: BigNumber;
      expiration: BigNumber;
      cost: BigNumber;
    }
  ] & {
    gId_: string;
    serviceId_: string;
    uuid: string;
    receipt: [string, string, BigNumber, BigNumber, BigNumber, BigNumber] & {
      to: string;
      token: string;
      level: BigNumber;
      boughtTime: BigNumber;
      expiration: BigNumber;
      cost: BigNumber;
    };
  }
>;

export type UpdateComboEvent = TypedEvent<
  [
    string,
    BigNumber,
    [BigNumber, BigNumber, BigNumber, BigNumber, string, boolean] & {
      bandwidth: BigNumber;
      storageAmount: BigNumber;
      buildingTime: BigNumber;
      pricePerMonth: BigNumber;
      to: string;
      isValid: boolean;
    }
  ] & {
    to: string;
    level: BigNumber;
    combo: [BigNumber, BigNumber, BigNumber, BigNumber, string, boolean] & {
      bandwidth: BigNumber;
      storageAmount: BigNumber;
      buildingTime: BigNumber;
      pricePerMonth: BigNumber;
      to: string;
      isValid: boolean;
    };
  }
>;

export type UpgradeEvent = TypedEvent<
  [
    string,
    string,
    string,
    [string, string, BigNumber, BigNumber, BigNumber, BigNumber] & {
      to: string;
      token: string;
      level: BigNumber;
      boughtTime: BigNumber;
      expiration: BigNumber;
      cost: BigNumber;
    }
  ] & {
    gId_: string;
    serviceId_: string;
    uuid: string;
    receipt: [string, string, BigNumber, BigNumber, BigNumber, BigNumber] & {
      to: string;
      token: string;
      level: BigNumber;
      boughtTime: BigNumber;
      expiration: BigNumber;
      cost: BigNumber;
    };
  }
>;

export class HostingPaymentV2 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: HostingPaymentV2Interface;

  functions: {
    Decimal(overrides?: CallOverrides): Promise<[BigNumber]>;

    MaxTotalExpiration(overrides?: CallOverrides): Promise<[BigNumber]>;

    MinExpiration(overrides?: CallOverrides): Promise<[BigNumber]>;

    addCombo(
      combo: {
        bandwidth: BigNumberish;
        storageAmount: BigNumberish;
        buildingTime: BigNumberish;
        pricePerMonth: BigNumberish;
        to: BytesLike;
        isValid: boolean;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    addManager(
      manager: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    addToken(
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    boughtTime(
      uuid: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    buy(
      uuid: BytesLike,
      tokenIndex: BigNumberish,
      level: BigNumberish,
      expiration_: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    canBuy(
      uuid: BytesLike,
      level: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    canRenew(uuid: BytesLike, overrides?: CallOverrides): Promise<[boolean]>;

    canUpgrade(
      uuid: BytesLike,
      level: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    channel(overrides?: CallOverrides): Promise<[string]>;

    comboLength(overrides?: CallOverrides): Promise<[BigNumber]>;

    combos(
      level: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        [BigNumber, BigNumber, BigNumber, BigNumber, string, boolean] & {
          bandwidth: BigNumber;
          storageAmount: BigNumber;
          buildingTime: BigNumber;
          pricePerMonth: BigNumber;
          to: string;
          isValid: boolean;
        }
      ]
    >;

    cost(uuid: BytesLike, overrides?: CallOverrides): Promise<[BigNumber]>;

    costToOriginalDecimal(
      cost: BigNumberish,
      tokenIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    decimalMethod(overrides?: CallOverrides): Promise<[string]>;

    decimals(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    expiration(
      uuid: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    expirationAt(
      uuid: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    gId(overrides?: CallOverrides): Promise<[string]>;

    getComboCost(
      level: BigNumberish,
      expiration_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { cost: BigNumber }>;

    getUpgradeExchange(
      uuid: BytesLike,
      level: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    guid(uuid: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    isCustom(
      level: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isExpired(uuid: BytesLike, overrides?: CallOverrides): Promise<[boolean]>;

    isManagers(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

    level(uuid: BytesLike, overrides?: CallOverrides): Promise<[BigNumber]>;

    lock(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    maxTotalRenewExpiration(
      uuid: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    maxTotalUpgradeExpiration(
      uuid: BytesLike,
      level: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    mints(overrides?: CallOverrides): Promise<[string]>;

    nonces(arg0: BytesLike, overrides?: CallOverrides): Promise<[BigNumber]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    receipts(
      uuid: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [
        [string, string, BigNumber, BigNumber, BigNumber, BigNumber] & {
          to: string;
          token: string;
          level: BigNumber;
          boughtTime: BigNumber;
          expiration: BigNumber;
          cost: BigNumber;
        }
      ]
    >;

    removeManager(
      manager: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    removeToken(
      index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    renew(
      nonce: BigNumberish,
      uuid: BytesLike,
      tokenIndex: BigNumberish,
      expiration_: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    serviceId(overrides?: CallOverrides): Promise<[string]>;

    setMaxTotalExpriation(
      expiration_: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setMinExpriation(
      expiration_: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    to(uuid: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    token(uuid: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    tokenLength(overrides?: CallOverrides): Promise<[BigNumber]>;

    tokens(index: BigNumberish, overrides?: CallOverrides): Promise<[string]>;

    transferChannel(
      channel_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    unlock(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateCombo(
      level: BigNumberish,
      combo: {
        bandwidth: BigNumberish;
        storageAmount: BigNumberish;
        buildingTime: BigNumberish;
        pricePerMonth: BigNumberish;
        to: BytesLike;
        isValid: boolean;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    upgrade(
      uuid: BytesLike,
      tokenIndex: BigNumberish,
      level: BigNumberish,
      moreExpiration: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    validateCombo(
      level: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[void]>;

    withdraw(
      token: string,
      to: string,
      value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  Decimal(overrides?: CallOverrides): Promise<BigNumber>;

  MaxTotalExpiration(overrides?: CallOverrides): Promise<BigNumber>;

  MinExpiration(overrides?: CallOverrides): Promise<BigNumber>;

  addCombo(
    combo: {
      bandwidth: BigNumberish;
      storageAmount: BigNumberish;
      buildingTime: BigNumberish;
      pricePerMonth: BigNumberish;
      to: BytesLike;
      isValid: boolean;
    },
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  addManager(
    manager: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  addToken(
    token: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  boughtTime(uuid: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

  buy(
    uuid: BytesLike,
    tokenIndex: BigNumberish,
    level: BigNumberish,
    expiration_: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  canBuy(
    uuid: BytesLike,
    level: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  canRenew(uuid: BytesLike, overrides?: CallOverrides): Promise<boolean>;

  canUpgrade(
    uuid: BytesLike,
    level: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  channel(overrides?: CallOverrides): Promise<string>;

  comboLength(overrides?: CallOverrides): Promise<BigNumber>;

  combos(
    level: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, BigNumber, string, boolean] & {
      bandwidth: BigNumber;
      storageAmount: BigNumber;
      buildingTime: BigNumber;
      pricePerMonth: BigNumber;
      to: string;
      isValid: boolean;
    }
  >;

  cost(uuid: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

  costToOriginalDecimal(
    cost: BigNumberish,
    tokenIndex: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  decimalMethod(overrides?: CallOverrides): Promise<string>;

  decimals(index: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

  expiration(uuid: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

  expirationAt(uuid: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

  gId(overrides?: CallOverrides): Promise<string>;

  getComboCost(
    level: BigNumberish,
    expiration_: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getUpgradeExchange(
    uuid: BytesLike,
    level: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  guid(uuid: BytesLike, overrides?: CallOverrides): Promise<string>;

  isCustom(level: BigNumberish, overrides?: CallOverrides): Promise<boolean>;

  isExpired(uuid: BytesLike, overrides?: CallOverrides): Promise<boolean>;

  isManagers(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  level(uuid: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

  lock(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  maxTotalRenewExpiration(
    uuid: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  maxTotalUpgradeExpiration(
    uuid: BytesLike,
    level: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  mints(overrides?: CallOverrides): Promise<string>;

  nonces(arg0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

  owner(overrides?: CallOverrides): Promise<string>;

  receipts(
    uuid: BytesLike,
    overrides?: CallOverrides
  ): Promise<
    [string, string, BigNumber, BigNumber, BigNumber, BigNumber] & {
      to: string;
      token: string;
      level: BigNumber;
      boughtTime: BigNumber;
      expiration: BigNumber;
      cost: BigNumber;
    }
  >;

  removeManager(
    manager: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  removeToken(
    index: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  renew(
    nonce: BigNumberish,
    uuid: BytesLike,
    tokenIndex: BigNumberish,
    expiration_: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  serviceId(overrides?: CallOverrides): Promise<string>;

  setMaxTotalExpriation(
    expiration_: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setMinExpriation(
    expiration_: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  to(uuid: BytesLike, overrides?: CallOverrides): Promise<string>;

  token(uuid: BytesLike, overrides?: CallOverrides): Promise<string>;

  tokenLength(overrides?: CallOverrides): Promise<BigNumber>;

  tokens(index: BigNumberish, overrides?: CallOverrides): Promise<string>;

  transferChannel(
    channel_: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  unlock(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateCombo(
    level: BigNumberish,
    combo: {
      bandwidth: BigNumberish;
      storageAmount: BigNumberish;
      buildingTime: BigNumberish;
      pricePerMonth: BigNumberish;
      to: BytesLike;
      isValid: boolean;
    },
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  upgrade(
    uuid: BytesLike,
    tokenIndex: BigNumberish,
    level: BigNumberish,
    moreExpiration: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  validateCombo(level: BigNumberish, overrides?: CallOverrides): Promise<void>;

  withdraw(
    token: string,
    to: string,
    value: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    Decimal(overrides?: CallOverrides): Promise<BigNumber>;

    MaxTotalExpiration(overrides?: CallOverrides): Promise<BigNumber>;

    MinExpiration(overrides?: CallOverrides): Promise<BigNumber>;

    addCombo(
      combo: {
        bandwidth: BigNumberish;
        storageAmount: BigNumberish;
        buildingTime: BigNumberish;
        pricePerMonth: BigNumberish;
        to: BytesLike;
        isValid: boolean;
      },
      overrides?: CallOverrides
    ): Promise<void>;

    addManager(manager: string, overrides?: CallOverrides): Promise<void>;

    addToken(token: string, overrides?: CallOverrides): Promise<void>;

    boughtTime(uuid: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    buy(
      uuid: BytesLike,
      tokenIndex: BigNumberish,
      level: BigNumberish,
      expiration_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    canBuy(
      uuid: BytesLike,
      level: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    canRenew(uuid: BytesLike, overrides?: CallOverrides): Promise<boolean>;

    canUpgrade(
      uuid: BytesLike,
      level: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    channel(overrides?: CallOverrides): Promise<string>;

    comboLength(overrides?: CallOverrides): Promise<BigNumber>;

    combos(
      level: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, string, boolean] & {
        bandwidth: BigNumber;
        storageAmount: BigNumber;
        buildingTime: BigNumber;
        pricePerMonth: BigNumber;
        to: string;
        isValid: boolean;
      }
    >;

    cost(uuid: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    costToOriginalDecimal(
      cost: BigNumberish,
      tokenIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    decimalMethod(overrides?: CallOverrides): Promise<string>;

    decimals(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    expiration(uuid: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    expirationAt(
      uuid: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    gId(overrides?: CallOverrides): Promise<string>;

    getComboCost(
      level: BigNumberish,
      expiration_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getUpgradeExchange(
      uuid: BytesLike,
      level: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    guid(uuid: BytesLike, overrides?: CallOverrides): Promise<string>;

    isCustom(level: BigNumberish, overrides?: CallOverrides): Promise<boolean>;

    isExpired(uuid: BytesLike, overrides?: CallOverrides): Promise<boolean>;

    isManagers(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    level(uuid: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    lock(overrides?: CallOverrides): Promise<void>;

    maxTotalRenewExpiration(
      uuid: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    maxTotalUpgradeExpiration(
      uuid: BytesLike,
      level: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    mints(overrides?: CallOverrides): Promise<string>;

    nonces(arg0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<string>;

    receipts(
      uuid: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [string, string, BigNumber, BigNumber, BigNumber, BigNumber] & {
        to: string;
        token: string;
        level: BigNumber;
        boughtTime: BigNumber;
        expiration: BigNumber;
        cost: BigNumber;
      }
    >;

    removeManager(manager: string, overrides?: CallOverrides): Promise<void>;

    removeToken(index: BigNumberish, overrides?: CallOverrides): Promise<void>;

    renew(
      nonce: BigNumberish,
      uuid: BytesLike,
      tokenIndex: BigNumberish,
      expiration_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    serviceId(overrides?: CallOverrides): Promise<string>;

    setMaxTotalExpriation(
      expiration_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setMinExpriation(
      expiration_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    to(uuid: BytesLike, overrides?: CallOverrides): Promise<string>;

    token(uuid: BytesLike, overrides?: CallOverrides): Promise<string>;

    tokenLength(overrides?: CallOverrides): Promise<BigNumber>;

    tokens(index: BigNumberish, overrides?: CallOverrides): Promise<string>;

    transferChannel(channel_: string, overrides?: CallOverrides): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    unlock(overrides?: CallOverrides): Promise<void>;

    updateCombo(
      level: BigNumberish,
      combo: {
        bandwidth: BigNumberish;
        storageAmount: BigNumberish;
        buildingTime: BigNumberish;
        pricePerMonth: BigNumberish;
        to: BytesLike;
        isValid: boolean;
      },
      overrides?: CallOverrides
    ): Promise<void>;

    upgrade(
      uuid: BytesLike,
      tokenIndex: BigNumberish,
      level: BigNumberish,
      moreExpiration: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    validateCombo(
      level: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    withdraw(
      token: string,
      to: string,
      value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "AddCombo(bytes28,uint256,tuple)"(
      to?: BytesLike | null,
      level?: BigNumberish | null,
      combo?: null
    ): TypedEventFilter<
      [
        string,
        BigNumber,
        [BigNumber, BigNumber, BigNumber, BigNumber, string, boolean] & {
          bandwidth: BigNumber;
          storageAmount: BigNumber;
          buildingTime: BigNumber;
          pricePerMonth: BigNumber;
          to: string;
          isValid: boolean;
        }
      ],
      {
        to: string;
        level: BigNumber;
        combo: [BigNumber, BigNumber, BigNumber, BigNumber, string, boolean] & {
          bandwidth: BigNumber;
          storageAmount: BigNumber;
          buildingTime: BigNumber;
          pricePerMonth: BigNumber;
          to: string;
          isValid: boolean;
        };
      }
    >;

    AddCombo(
      to?: BytesLike | null,
      level?: BigNumberish | null,
      combo?: null
    ): TypedEventFilter<
      [
        string,
        BigNumber,
        [BigNumber, BigNumber, BigNumber, BigNumber, string, boolean] & {
          bandwidth: BigNumber;
          storageAmount: BigNumber;
          buildingTime: BigNumber;
          pricePerMonth: BigNumber;
          to: string;
          isValid: boolean;
        }
      ],
      {
        to: string;
        level: BigNumber;
        combo: [BigNumber, BigNumber, BigNumber, BigNumber, string, boolean] & {
          bandwidth: BigNumber;
          storageAmount: BigNumber;
          buildingTime: BigNumber;
          pricePerMonth: BigNumber;
          to: string;
          isValid: boolean;
        };
      }
    >;

    "AddManager(address)"(
      manager?: string | null
    ): TypedEventFilter<[string], { manager: string }>;

    AddManager(
      manager?: string | null
    ): TypedEventFilter<[string], { manager: string }>;

    "AddToken(uint256,address)"(
      index?: BigNumberish | null,
      token?: string | null
    ): TypedEventFilter<
      [BigNumber, string],
      { index: BigNumber; token: string }
    >;

    AddToken(
      index?: BigNumberish | null,
      token?: string | null
    ): TypedEventFilter<
      [BigNumber, string],
      { index: BigNumber; token: string }
    >;

    "Buy(bytes2,bytes2,bytes28,tuple)"(
      gId_?: BytesLike | null,
      serviceId_?: BytesLike | null,
      uuid?: BytesLike | null,
      receipt?: null
    ): TypedEventFilter<
      [
        string,
        string,
        string,
        [string, string, BigNumber, BigNumber, BigNumber, BigNumber] & {
          to: string;
          token: string;
          level: BigNumber;
          boughtTime: BigNumber;
          expiration: BigNumber;
          cost: BigNumber;
        }
      ],
      {
        gId_: string;
        serviceId_: string;
        uuid: string;
        receipt: [
          string,
          string,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ] & {
          to: string;
          token: string;
          level: BigNumber;
          boughtTime: BigNumber;
          expiration: BigNumber;
          cost: BigNumber;
        };
      }
    >;

    Buy(
      gId_?: BytesLike | null,
      serviceId_?: BytesLike | null,
      uuid?: BytesLike | null,
      receipt?: null
    ): TypedEventFilter<
      [
        string,
        string,
        string,
        [string, string, BigNumber, BigNumber, BigNumber, BigNumber] & {
          to: string;
          token: string;
          level: BigNumber;
          boughtTime: BigNumber;
          expiration: BigNumber;
          cost: BigNumber;
        }
      ],
      {
        gId_: string;
        serviceId_: string;
        uuid: string;
        receipt: [
          string,
          string,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ] & {
          to: string;
          token: string;
          level: BigNumber;
          boughtTime: BigNumber;
          expiration: BigNumber;
          cost: BigNumber;
        };
      }
    >;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    "RemoveManager(address)"(
      manager?: string | null
    ): TypedEventFilter<[string], { manager: string }>;

    RemoveManager(
      manager?: string | null
    ): TypedEventFilter<[string], { manager: string }>;

    "RemoveToken(uint256,address)"(
      index?: BigNumberish | null,
      token?: string | null
    ): TypedEventFilter<
      [BigNumber, string],
      { index: BigNumber; token: string }
    >;

    RemoveToken(
      index?: BigNumberish | null,
      token?: string | null
    ): TypedEventFilter<
      [BigNumber, string],
      { index: BigNumber; token: string }
    >;

    "Renew(bytes2,bytes2,bytes28,tuple)"(
      gId_?: BytesLike | null,
      serviceId_?: BytesLike | null,
      uuid?: BytesLike | null,
      receipt?: null
    ): TypedEventFilter<
      [
        string,
        string,
        string,
        [string, string, BigNumber, BigNumber, BigNumber, BigNumber] & {
          to: string;
          token: string;
          level: BigNumber;
          boughtTime: BigNumber;
          expiration: BigNumber;
          cost: BigNumber;
        }
      ],
      {
        gId_: string;
        serviceId_: string;
        uuid: string;
        receipt: [
          string,
          string,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ] & {
          to: string;
          token: string;
          level: BigNumber;
          boughtTime: BigNumber;
          expiration: BigNumber;
          cost: BigNumber;
        };
      }
    >;

    Renew(
      gId_?: BytesLike | null,
      serviceId_?: BytesLike | null,
      uuid?: BytesLike | null,
      receipt?: null
    ): TypedEventFilter<
      [
        string,
        string,
        string,
        [string, string, BigNumber, BigNumber, BigNumber, BigNumber] & {
          to: string;
          token: string;
          level: BigNumber;
          boughtTime: BigNumber;
          expiration: BigNumber;
          cost: BigNumber;
        }
      ],
      {
        gId_: string;
        serviceId_: string;
        uuid: string;
        receipt: [
          string,
          string,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ] & {
          to: string;
          token: string;
          level: BigNumber;
          boughtTime: BigNumber;
          expiration: BigNumber;
          cost: BigNumber;
        };
      }
    >;

    "UpdateCombo(bytes28,uint256,tuple)"(
      to?: BytesLike | null,
      level?: BigNumberish | null,
      combo?: null
    ): TypedEventFilter<
      [
        string,
        BigNumber,
        [BigNumber, BigNumber, BigNumber, BigNumber, string, boolean] & {
          bandwidth: BigNumber;
          storageAmount: BigNumber;
          buildingTime: BigNumber;
          pricePerMonth: BigNumber;
          to: string;
          isValid: boolean;
        }
      ],
      {
        to: string;
        level: BigNumber;
        combo: [BigNumber, BigNumber, BigNumber, BigNumber, string, boolean] & {
          bandwidth: BigNumber;
          storageAmount: BigNumber;
          buildingTime: BigNumber;
          pricePerMonth: BigNumber;
          to: string;
          isValid: boolean;
        };
      }
    >;

    UpdateCombo(
      to?: BytesLike | null,
      level?: BigNumberish | null,
      combo?: null
    ): TypedEventFilter<
      [
        string,
        BigNumber,
        [BigNumber, BigNumber, BigNumber, BigNumber, string, boolean] & {
          bandwidth: BigNumber;
          storageAmount: BigNumber;
          buildingTime: BigNumber;
          pricePerMonth: BigNumber;
          to: string;
          isValid: boolean;
        }
      ],
      {
        to: string;
        level: BigNumber;
        combo: [BigNumber, BigNumber, BigNumber, BigNumber, string, boolean] & {
          bandwidth: BigNumber;
          storageAmount: BigNumber;
          buildingTime: BigNumber;
          pricePerMonth: BigNumber;
          to: string;
          isValid: boolean;
        };
      }
    >;

    "Upgrade(bytes2,bytes2,bytes28,tuple)"(
      gId_?: BytesLike | null,
      serviceId_?: BytesLike | null,
      uuid?: BytesLike | null,
      receipt?: null
    ): TypedEventFilter<
      [
        string,
        string,
        string,
        [string, string, BigNumber, BigNumber, BigNumber, BigNumber] & {
          to: string;
          token: string;
          level: BigNumber;
          boughtTime: BigNumber;
          expiration: BigNumber;
          cost: BigNumber;
        }
      ],
      {
        gId_: string;
        serviceId_: string;
        uuid: string;
        receipt: [
          string,
          string,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ] & {
          to: string;
          token: string;
          level: BigNumber;
          boughtTime: BigNumber;
          expiration: BigNumber;
          cost: BigNumber;
        };
      }
    >;

    Upgrade(
      gId_?: BytesLike | null,
      serviceId_?: BytesLike | null,
      uuid?: BytesLike | null,
      receipt?: null
    ): TypedEventFilter<
      [
        string,
        string,
        string,
        [string, string, BigNumber, BigNumber, BigNumber, BigNumber] & {
          to: string;
          token: string;
          level: BigNumber;
          boughtTime: BigNumber;
          expiration: BigNumber;
          cost: BigNumber;
        }
      ],
      {
        gId_: string;
        serviceId_: string;
        uuid: string;
        receipt: [
          string,
          string,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ] & {
          to: string;
          token: string;
          level: BigNumber;
          boughtTime: BigNumber;
          expiration: BigNumber;
          cost: BigNumber;
        };
      }
    >;
  };

  estimateGas: {
    Decimal(overrides?: CallOverrides): Promise<BigNumber>;

    MaxTotalExpiration(overrides?: CallOverrides): Promise<BigNumber>;

    MinExpiration(overrides?: CallOverrides): Promise<BigNumber>;

    addCombo(
      combo: {
        bandwidth: BigNumberish;
        storageAmount: BigNumberish;
        buildingTime: BigNumberish;
        pricePerMonth: BigNumberish;
        to: BytesLike;
        isValid: boolean;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    addManager(
      manager: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    addToken(
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    boughtTime(uuid: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    buy(
      uuid: BytesLike,
      tokenIndex: BigNumberish,
      level: BigNumberish,
      expiration_: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    canBuy(
      uuid: BytesLike,
      level: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    canRenew(uuid: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    canUpgrade(
      uuid: BytesLike,
      level: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    channel(overrides?: CallOverrides): Promise<BigNumber>;

    comboLength(overrides?: CallOverrides): Promise<BigNumber>;

    combos(level: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    cost(uuid: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    costToOriginalDecimal(
      cost: BigNumberish,
      tokenIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    decimalMethod(overrides?: CallOverrides): Promise<BigNumber>;

    decimals(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    expiration(uuid: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    expirationAt(
      uuid: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    gId(overrides?: CallOverrides): Promise<BigNumber>;

    getComboCost(
      level: BigNumberish,
      expiration_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getUpgradeExchange(
      uuid: BytesLike,
      level: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    guid(uuid: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    isCustom(
      level: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isExpired(uuid: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    isManagers(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    level(uuid: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    lock(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    maxTotalRenewExpiration(
      uuid: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    maxTotalUpgradeExpiration(
      uuid: BytesLike,
      level: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    mints(overrides?: CallOverrides): Promise<BigNumber>;

    nonces(arg0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    receipts(uuid: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    removeManager(
      manager: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    removeToken(
      index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    renew(
      nonce: BigNumberish,
      uuid: BytesLike,
      tokenIndex: BigNumberish,
      expiration_: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    serviceId(overrides?: CallOverrides): Promise<BigNumber>;

    setMaxTotalExpriation(
      expiration_: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setMinExpriation(
      expiration_: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    to(uuid: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    token(uuid: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    tokenLength(overrides?: CallOverrides): Promise<BigNumber>;

    tokens(index: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    transferChannel(
      channel_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    unlock(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateCombo(
      level: BigNumberish,
      combo: {
        bandwidth: BigNumberish;
        storageAmount: BigNumberish;
        buildingTime: BigNumberish;
        pricePerMonth: BigNumberish;
        to: BytesLike;
        isValid: boolean;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    upgrade(
      uuid: BytesLike,
      tokenIndex: BigNumberish,
      level: BigNumberish,
      moreExpiration: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    validateCombo(
      level: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdraw(
      token: string,
      to: string,
      value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    Decimal(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    MaxTotalExpiration(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    MinExpiration(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    addCombo(
      combo: {
        bandwidth: BigNumberish;
        storageAmount: BigNumberish;
        buildingTime: BigNumberish;
        pricePerMonth: BigNumberish;
        to: BytesLike;
        isValid: boolean;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    addManager(
      manager: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    addToken(
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    boughtTime(
      uuid: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    buy(
      uuid: BytesLike,
      tokenIndex: BigNumberish,
      level: BigNumberish,
      expiration_: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    canBuy(
      uuid: BytesLike,
      level: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    canRenew(
      uuid: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    canUpgrade(
      uuid: BytesLike,
      level: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    channel(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    comboLength(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    combos(
      level: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    cost(
      uuid: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    costToOriginalDecimal(
      cost: BigNumberish,
      tokenIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    decimalMethod(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    decimals(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    expiration(
      uuid: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    expirationAt(
      uuid: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    gId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getComboCost(
      level: BigNumberish,
      expiration_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getUpgradeExchange(
      uuid: BytesLike,
      level: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    guid(
      uuid: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isCustom(
      level: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isExpired(
      uuid: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isManagers(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    level(
      uuid: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    lock(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    maxTotalRenewExpiration(
      uuid: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    maxTotalUpgradeExpiration(
      uuid: BytesLike,
      level: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    mints(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    nonces(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    receipts(
      uuid: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    removeManager(
      manager: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    removeToken(
      index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    renew(
      nonce: BigNumberish,
      uuid: BytesLike,
      tokenIndex: BigNumberish,
      expiration_: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    serviceId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setMaxTotalExpriation(
      expiration_: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setMinExpriation(
      expiration_: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    to(
      uuid: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    token(
      uuid: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tokenLength(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    tokens(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferChannel(
      channel_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    unlock(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateCombo(
      level: BigNumberish,
      combo: {
        bandwidth: BigNumberish;
        storageAmount: BigNumberish;
        buildingTime: BigNumberish;
        pricePerMonth: BigNumberish;
        to: BytesLike;
        isValid: boolean;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    upgrade(
      uuid: BytesLike,
      tokenIndex: BigNumberish,
      level: BigNumberish,
      moreExpiration: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    validateCombo(
      level: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    withdraw(
      token: string,
      to: string,
      value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
