/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IRootChannel, IRootChannelInterface } from "../IRootChannel";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "inputData",
        type: "bytes",
      },
    ],
    name: "receiveMessage",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "message",
        type: "bytes",
      },
    ],
    name: "sendMessageToChild",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_childChannel",
        type: "address",
      },
    ],
    name: "setChildChannel",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IRootChannel__factory {
  static readonly abi = _abi;
  static createInterface(): IRootChannelInterface {
    return new utils.Interface(_abi) as IRootChannelInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRootChannel {
    return new Contract(address, _abi, signerOrProvider) as IRootChannel;
  }
}
